
#spring 기본설정
spring:
  jmx:
    enabled: false
  datasource:
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 임시 URL
    # url: jdbc:log4jdbc:sqlserver://devdb.cesco.biz:11433;DatabaseName=CESCOFS;
    # url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=CESCOFS;
    url: jdbc:mysql://localhost:3306/admin?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 30000
      poolName: maindb-pool
      maxLifetime: 2000000
      connectionTimeout: 30000
  mail:
    host: smtp.gmail.com
    port: 587
    username: navycuicool@yahoo.com
    password: 123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10000000MB
      max-request-size: 10000000MB
      # location: D:/labelingconsulting/upload/images/
      location: /fsccs/tomcat9/images/

server:  
  servlet:    
    session:      
      timeout: 150000
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  

################################
# LOGGING
#################################
logging:
   pattern:
      console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%4line]){magenta} %clr(%-40.40logger{39}){cyan} %clr(:){red} %m%n%wEx'
   level:
      root: info
      aicluster: debug
      jdbc:
         resultset: error
         audit: error
  # file:
  #   max-size: 500MB
  #   max-history: 10
    # path: D:/labelingconsulting/logs

#============================================================================
# SFTP Client Setting
#============================================================================
sftp:
  client:
    host: 112.169.182.196
    port: 22
    protocol: sftp 
    username: fsccs
    password: Ces@Fs#CCS!2310
    root: /fsccs/ftp/fsftp/
    rootHc: /fsccs/ftp/hcftp/
    sessionStrictHostKeyChecking: no
    sessionConnectTimeout: 150000
    channelConnectedTimeout: 150000

#################################
# E-FORM 
#################################
eform:
  client:
    host: 172.18.1.41
    port: 22
    protocol: sftp 
    username: fsccs
    password: Ces@Fs#CCS!2310
    root: /file/fsccs/
    rootHc: /file/fsccs/
    sessionStrictHostKeyChecking: no
    sessionConnectTimeout: 150000
    channelConnectedTimeout: 150000

eformLoc: https://deveform.cesco.co.kr
eform.crf.dir: /ecm/eform/
#ftpip: kftc.cesco.biz
#ftpid: kftcftp
#ftppwd: Cesco@Ftp#3019
#ftpport: 38383
#ftpdir: Evidence
